@Spracher.Api_HostAddress = http://localhost:5180

GET {{Spracher.Api_HostAddress}}/api/v1/system/info
Accept: application/json

###

GET {{Spracher.Api_HostAddress}}/health/live

###

GET {{Spracher.Api_HostAddress}}/health/ready

###
