// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spracher.Persistence;

#nullable disable

namespace Spracher.Persistence.Migrations
{
    [DbContext(typeof(SpracherDbContext))]
    [Migration("20260814214617_OptimizeVocabularyPrefixSearch")]
    partial class OptimizeVocabularyPrefixSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "iam");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "iam");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "iam");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "iam");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "iam");
                });

            modelBuilder.Entity("Spracher.IdentityModel.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", "iam");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198ac40-0000-7000-8000-000000000001"),
                            ConcurrencyStamp = "role-self-learner-v1",
                            Name = "SelfLearner",
                            NormalizedName = "SELFLEARNER"
                        },
                        new
                        {
                            Id = new Guid("0198ac40-0000-7000-8000-000000000002"),
                            ConcurrencyStamp = "role-student-v1",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = new Guid("0198ac40-0000-7000-8000-000000000003"),
                            ConcurrencyStamp = "role-teacher-v1",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = new Guid("0198ac40-0000-7000-8000-000000000004"),
                            ConcurrencyStamp = "role-admin-v1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("0198ac40-0000-7000-8000-000000000005"),
                            ConcurrencyStamp = "role-school-admin-v1",
                            Name = "SchoolAdmin",
                            NormalizedName = "SCHOOLADMIN"
                        });
                });

            modelBuilder.Entity("Spracher.IdentityModel.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ProfileUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", "iam");
                });

            modelBuilder.Entity("Spracher.Modules.Exercises.Domain.ExerciseAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AwardedPoints")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseVersionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseVersionId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("ExerciseAttempts", "exercises", t =>
                        {
                            t.HasCheckConstraint("CK_ExerciseAttempts_Score", "(\"AwardedPoints\" IS NULL AND \"MaxPoints\" IS NULL) OR (\"AwardedPoints\" >= 0 AND \"MaxPoints\" > 0 AND \"AwardedPoints\" <= \"MaxPoints\")");
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Exercises.Domain.ExerciseDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey", "ArchivedAt");

                    b.ToTable("ExerciseDefinitions", "exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198b100-0000-7000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Choose the correct verb form for he, she or it.",
                            Title = "Present Simple: third person",
                            TypeKey = "multiple-choice"
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Exercises.Domain.ExerciseSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("AwardedPoints")
                        .HasColumnType("integer");

                    b.Property<string>("GradingJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.ToTable("ExerciseSubmissions", "exercises", t =>
                        {
                            t.HasCheckConstraint("CK_ExerciseSubmissions_Score", "\"AwardedPoints\" >= 0 AND \"MaxPoints\" > 0 AND \"AwardedPoints\" <= \"MaxPoints\"");
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Exercises.Domain.ExerciseVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("ExerciseDefinitionId", "Status", "VersionNumber");

                    b.ToTable("ExerciseVersions", "exercises", t =>
                        {
                            t.HasCheckConstraint("CK_ExerciseVersions_Schema", "\"SchemaVersion\" > 0");

                            t.HasCheckConstraint("CK_ExerciseVersions_Version", "\"VersionNumber\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198b110-0000-7000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefinitionJson = "{\n  \"options\": [\n    { \"id\": \"work\", \"text\": \"She work in a bank.\" },\n    { \"id\": \"works\", \"text\": \"She works in a bank.\" },\n    { \"id\": \"working\", \"text\": \"She working in a bank.\" }\n  ],\n  \"correctOptionIds\": [\"works\"],\n  \"points\": 10,\n  \"correctFeedback\": \"Exactly — use -s with she in the Present Simple.\",\n  \"incorrectFeedback\": \"Remember: in the Present Simple, he/she/it takes -s.\"\n}",
                            ExerciseDefinitionId = new Guid("0198b100-0000-7000-8000-000000000001"),
                            Prompt = "Choose the correct sentence.",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SchemaVersion = 1,
                            Status = "Published",
                            VersionNumber = 1
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Languages.Domain.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TextDirection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", "languages", t =>
                        {
                            t.HasCheckConstraint("CK_Languages_TextDirection", "\"TextDirection\" IN ('LeftToRight', 'RightToLeft')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            Code = "pl",
                            IsActive = true,
                            Name = "Polish",
                            NativeName = "Polski",
                            TextDirection = "LeftToRight"
                        },
                        new
                        {
                            Id = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            Code = "en",
                            IsActive = true,
                            Name = "English",
                            NativeName = "English",
                            TextDirection = "LeftToRight"
                        },
                        new
                        {
                            Id = new Guid("0198ac50-0000-7000-8000-000000000003"),
                            Code = "de",
                            IsActive = true,
                            Name = "German",
                            NativeName = "Deutsch",
                            TextDirection = "LeftToRight"
                        },
                        new
                        {
                            Id = new Guid("0198ac50-0000-7000-8000-000000000004"),
                            Code = "es",
                            IsActive = true,
                            Name = "Spanish",
                            NativeName = "Español",
                            TextDirection = "LeftToRight"
                        },
                        new
                        {
                            Id = new Guid("0198ac50-0000-7000-8000-000000000005"),
                            Code = "fr",
                            IsActive = true,
                            Name = "French",
                            NativeName = "Français",
                            TextDirection = "LeftToRight"
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Languages.Domain.UserLanguageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentCefrLevel")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("IsLearning")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNative")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique();

                    b.ToTable("UserLanguageProfiles", "languages", t =>
                        {
                            t.HasCheckConstraint("CK_UserLanguageProfiles_CefrLevel", "\"CurrentCefrLevel\" IS NULL OR \"CurrentCefrLevel\" IN ('A0', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2')");

                            t.HasCheckConstraint("CK_UserLanguageProfiles_LearningState", "(\"IsLearning\" AND \"CurrentCefrLevel\" IS NOT NULL AND \"StartedAt\" IS NOT NULL) OR (NOT \"IsLearning\" AND \"CurrentCefrLevel\" IS NULL AND \"StartedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_UserLanguageProfiles_Selected", "\"IsNative\" OR \"IsLearning\"");
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Visibility");

                    b.ToTable("Concepts", "vocabulary", t =>
                        {
                            t.HasCheckConstraint("CK_Concepts_Ownership", "(\"Visibility\" = 'Catalog' AND \"OwnerUserId\" IS NULL) OR (\"Visibility\" = 'Private' AND \"OwnerUserId\" IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198ae00-0000-7000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Key = "bank.financial-institution",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae00-0000-7000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Key = "bank.river-edge",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae00-0000-7000-8000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Key = "run.move-quickly",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae00-0000-7000-8000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Key = "apple.fruit",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.ExampleSentence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("ExampleSentences", "vocabulary", t =>
                        {
                            t.HasCheckConstraint("CK_ExampleSentences_Ownership", "(\"Visibility\" = 'Catalog' AND \"OwnerUserId\" IS NULL) OR (\"Visibility\" = 'Private' AND \"OwnerUserId\" IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198ae60-0000-7000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            Text = "She works at a bank in the city centre.",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae60-0000-7000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            Text = "We sat on the river bank.",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae60-0000-7000-8000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            Text = "Usiedliśmy na brzegu rzeki.",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae60-0000-7000-8000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            Text = "I run every morning.",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae60-0000-7000-8000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            Text = "Lubię biec rano.",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae60-0000-7000-8000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            Text = "This apple is sweet.",
                            Visibility = "Catalog"
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.ExampleUsage", b =>
                {
                    b.Property<Guid>("LexemeSenseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExampleSentenceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("HighlightLength")
                        .HasColumnType("integer");

                    b.Property<int?>("HighlightStart")
                        .HasColumnType("integer");

                    b.HasKey("LexemeSenseId", "ExampleSentenceId");

                    b.HasIndex("ExampleSentenceId");

                    b.ToTable("ExampleUsages", "vocabulary", t =>
                        {
                            t.HasCheckConstraint("CK_ExampleUsages_Highlight", "(\"HighlightStart\" IS NULL AND \"HighlightLength\" IS NULL) OR (\"HighlightStart\" >= 0 AND \"HighlightLength\" > 0)");
                        });

                    b.HasData(
                        new
                        {
                            LexemeSenseId = new Guid("0198ae20-0000-7000-8000-000000000001"),
                            ExampleSentenceId = new Guid("0198ae60-0000-7000-8000-000000000001"),
                            HighlightLength = 4,
                            HighlightStart = 15
                        },
                        new
                        {
                            LexemeSenseId = new Guid("0198ae20-0000-7000-8000-000000000002"),
                            ExampleSentenceId = new Guid("0198ae60-0000-7000-8000-000000000002"),
                            HighlightLength = 4,
                            HighlightStart = 20
                        },
                        new
                        {
                            LexemeSenseId = new Guid("0198ae20-0000-7000-8000-000000000004"),
                            ExampleSentenceId = new Guid("0198ae60-0000-7000-8000-000000000003"),
                            HighlightLength = 6,
                            HighlightStart = 14
                        },
                        new
                        {
                            LexemeSenseId = new Guid("0198ae20-0000-7000-8000-000000000005"),
                            ExampleSentenceId = new Guid("0198ae60-0000-7000-8000-000000000004"),
                            HighlightLength = 3,
                            HighlightStart = 2
                        },
                        new
                        {
                            LexemeSenseId = new Guid("0198ae20-0000-7000-8000-000000000006"),
                            ExampleSentenceId = new Guid("0198ae60-0000-7000-8000-000000000005"),
                            HighlightLength = 4,
                            HighlightStart = 5
                        },
                        new
                        {
                            LexemeSenseId = new Guid("0198ae20-0000-7000-8000-000000000007"),
                            ExampleSentenceId = new Guid("0198ae60-0000-7000-8000-000000000006"),
                            HighlightLength = 5,
                            HighlightStart = 5
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.Lexeme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CefrLevel")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("integer");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedLemma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyRank");

                    b.HasIndex("LanguageId", "NormalizedLemma");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("LanguageId", "NormalizedLemma"), new[] { "uuid_ops", "text_pattern_ops" });

                    b.HasIndex("PublicationStatus", "CefrLevel");

                    b.HasIndex("LanguageId", "PartOfSpeech", "NormalizedLemma");

                    b.HasIndex("OwnerUserId", "LanguageId", "PartOfSpeech", "NormalizedLemma")
                        .IsUnique()
                        .HasFilter("\"OwnerUserId\" IS NOT NULL");

                    b.ToTable("Lexemes", "vocabulary", t =>
                        {
                            t.HasCheckConstraint("CK_Lexemes_FrequencyRank", "\"FrequencyRank\" IS NULL OR \"FrequencyRank\" > 0");

                            t.HasCheckConstraint("CK_Lexemes_Ownership", "(\"Visibility\" = 'Catalog' AND \"OwnerUserId\" IS NULL) OR (\"Visibility\" = 'Private' AND \"OwnerUserId\" IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198ae10-0000-7000-8000-000000000001"),
                            CefrLevel = "A2",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FrequencyRank = 520,
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            Lemma = "bank",
                            NormalizedLemma = "bank",
                            PartOfSpeech = "Noun",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae10-0000-7000-8000-000000000002"),
                            CefrLevel = "A2",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FrequencyRank = 780,
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            Lemma = "bank",
                            NormalizedLemma = "bank",
                            PartOfSpeech = "Noun",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae10-0000-7000-8000-000000000003"),
                            CefrLevel = "A2",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FrequencyRank = 690,
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            Lemma = "brzeg",
                            NormalizedLemma = "brzeg",
                            PartOfSpeech = "Noun",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae10-0000-7000-8000-000000000004"),
                            CefrLevel = "A1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FrequencyRank = 180,
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            Lemma = "run",
                            NormalizedLemma = "run",
                            PartOfSpeech = "Verb",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae10-0000-7000-8000-000000000005"),
                            CefrLevel = "A1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FrequencyRank = 410,
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            Lemma = "biec",
                            NormalizedLemma = "biec",
                            PartOfSpeech = "Verb",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae10-0000-7000-8000-000000000006"),
                            CefrLevel = "A1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FrequencyRank = 1120,
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            Lemma = "apple",
                            NormalizedLemma = "apple",
                            PartOfSpeech = "Noun",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae10-0000-7000-8000-000000000007"),
                            CefrLevel = "A1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FrequencyRank = 990,
                            LanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            Lemma = "jabłko",
                            NormalizedLemma = "jabłko",
                            PartOfSpeech = "Noun",
                            PublicationStatus = "Published",
                            SourceReference = "spracher-curated-en-pl-v1",
                            SourceType = "Curated",
                            Visibility = "Catalog"
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.LexemeFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("LexemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("LexemeId", "Key", "Value")
                        .IsUnique();

                    b.ToTable("LexemeFeatures", "vocabulary");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198ae50-0000-7000-8000-000000000001"),
                            Key = "gender",
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000002"),
                            Value = "masculine"
                        },
                        new
                        {
                            Id = new Guid("0198ae50-0000-7000-8000-000000000002"),
                            Key = "gender",
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000003"),
                            Value = "masculine"
                        },
                        new
                        {
                            Id = new Guid("0198ae50-0000-7000-8000-000000000003"),
                            Key = "gender",
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000007"),
                            Value = "neuter"
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.LexemeSense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CefrLevelOverride")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DefinitionLanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LexemeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Register")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("DefinitionLanguageId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("LexemeId", "ConceptId");

                    b.ToTable("LexemeSenses", "vocabulary", t =>
                        {
                            t.HasCheckConstraint("CK_LexemeSenses_Ownership", "(\"Visibility\" = 'Catalog' AND \"OwnerUserId\" IS NULL) OR (\"Visibility\" = 'Private' AND \"OwnerUserId\" IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198ae20-0000-7000-8000-000000000001"),
                            ConceptId = new Guid("0198ae00-0000-7000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Definition = "An organization that keeps, lends, and exchanges money.",
                            DefinitionLanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000001"),
                            PublicationStatus = "Published",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae20-0000-7000-8000-000000000002"),
                            ConceptId = new Guid("0198ae00-0000-7000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Definition = "The land along the edge of a river.",
                            DefinitionLanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000001"),
                            PublicationStatus = "Published",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae20-0000-7000-8000-000000000003"),
                            ConceptId = new Guid("0198ae00-0000-7000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Definition = "Instytucja przechowująca pieniądze i udzielająca pożyczek.",
                            DefinitionLanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000002"),
                            PublicationStatus = "Published",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae20-0000-7000-8000-000000000004"),
                            ConceptId = new Guid("0198ae00-0000-7000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Definition = "Pas lądu znajdujący się przy rzece.",
                            DefinitionLanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000003"),
                            PublicationStatus = "Published",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae20-0000-7000-8000-000000000005"),
                            ConceptId = new Guid("0198ae00-0000-7000-8000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Definition = "To move quickly on foot.",
                            DefinitionLanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000004"),
                            PublicationStatus = "Published",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae20-0000-7000-8000-000000000006"),
                            ConceptId = new Guid("0198ae00-0000-7000-8000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Definition = "Poruszać się szybko, odbijając się stopami od podłoża.",
                            DefinitionLanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000005"),
                            PublicationStatus = "Published",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae20-0000-7000-8000-000000000007"),
                            ConceptId = new Guid("0198ae00-0000-7000-8000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Definition = "A round fruit with firm flesh and thin skin.",
                            DefinitionLanguageId = new Guid("0198ac50-0000-7000-8000-000000000002"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000006"),
                            PublicationStatus = "Published",
                            Visibility = "Catalog"
                        },
                        new
                        {
                            Id = new Guid("0198ae20-0000-7000-8000-000000000008"),
                            ConceptId = new Guid("0198ae00-0000-7000-8000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Definition = "Okrągły owoc jabłoni o cienkiej skórce.",
                            DefinitionLanguageId = new Guid("0198ac50-0000-7000-8000-000000000001"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000007"),
                            PublicationStatus = "Published",
                            Visibility = "Catalog"
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.Pronunciation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioAssetReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LexemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("LexemeId");

                    b.ToTable("Pronunciations", "vocabulary");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198ae40-0000-7000-8000-000000000001"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000001"),
                            Region = "en",
                            Scheme = "IPA",
                            Value = "/bæŋk/"
                        },
                        new
                        {
                            Id = new Guid("0198ae40-0000-7000-8000-000000000002"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000004"),
                            Region = "en",
                            Scheme = "IPA",
                            Value = "/rʌn/"
                        },
                        new
                        {
                            Id = new Guid("0198ae40-0000-7000-8000-000000000003"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000006"),
                            Region = "en",
                            Scheme = "IPA",
                            Value = "/ˈæp.əl/"
                        },
                        new
                        {
                            Id = new Guid("0198ae40-0000-7000-8000-000000000004"),
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000007"),
                            Region = "pl",
                            Scheme = "IPA",
                            Value = "/ˈjap.kɔ/"
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.UserVocabularyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LexemeSenseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LexemeSenseId");

                    b.HasIndex("UserId", "LexemeSenseId")
                        .IsUnique();

                    b.HasIndex("UserId", "Status", "StatusChangedAt");

                    b.ToTable("UserVocabularyItems", "vocabulary");
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.UserVocabularyItemCategory", b =>
                {
                    b.Property<Guid>("UserVocabularyItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VocabularyCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserVocabularyItemId", "VocabularyCategoryId");

                    b.HasIndex("VocabularyCategoryId");

                    b.ToTable("UserVocabularyItemCategories", "vocabulary");
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.VocabularyCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("VocabularyCategories", "vocabulary");
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.VocabularyList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("VocabularyLists", "vocabulary");
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.VocabularyListItem", b =>
                {
                    b.Property<Guid>("VocabularyListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LexemeSenseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("VocabularyListId", "LexemeSenseId");

                    b.HasIndex("LexemeSenseId");

                    b.HasIndex("VocabularyListId", "Position");

                    b.ToTable("VocabularyListItems", "vocabulary", t =>
                        {
                            t.HasCheckConstraint("CK_VocabularyListItems_Position", "\"Position\" >= 0");
                        });
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.WordForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GrammarTags")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("LexemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedForm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LexemeId", "NormalizedForm");

                    b.ToTable("WordForms", "vocabulary");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198ae30-0000-7000-8000-000000000001"),
                            Form = "banks",
                            GrammarTags = "plural",
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000001"),
                            NormalizedForm = "banks"
                        },
                        new
                        {
                            Id = new Guid("0198ae30-0000-7000-8000-000000000002"),
                            Form = "ran",
                            GrammarTags = "past",
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000004"),
                            NormalizedForm = "ran"
                        },
                        new
                        {
                            Id = new Guid("0198ae30-0000-7000-8000-000000000003"),
                            Form = "running",
                            GrammarTags = "present-participle",
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000004"),
                            NormalizedForm = "running"
                        },
                        new
                        {
                            Id = new Guid("0198ae30-0000-7000-8000-000000000004"),
                            Form = "apples",
                            GrammarTags = "plural",
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000006"),
                            NormalizedForm = "apples"
                        },
                        new
                        {
                            Id = new Guid("0198ae30-0000-7000-8000-000000000005"),
                            Form = "jabłka",
                            GrammarTags = "genitive-singular;nominative-plural",
                            LexemeId = new Guid("0198ae10-0000-7000-8000-000000000007"),
                            NormalizedForm = "jabłka"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Spracher.IdentityModel.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Spracher.IdentityModel.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Exercises.Domain.ExerciseAttempt", b =>
                {
                    b.HasOne("Spracher.Modules.Exercises.Domain.ExerciseVersion", null)
                        .WithMany()
                        .HasForeignKey("ExerciseVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Exercises.Domain.ExerciseSubmission", b =>
                {
                    b.HasOne("Spracher.Modules.Exercises.Domain.ExerciseAttempt", null)
                        .WithOne()
                        .HasForeignKey("Spracher.Modules.Exercises.Domain.ExerciseSubmission", "AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Exercises.Domain.ExerciseVersion", b =>
                {
                    b.HasOne("Spracher.Modules.Exercises.Domain.ExerciseDefinition", null)
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Languages.Domain.UserLanguageProfile", b =>
                {
                    b.HasOne("Spracher.Modules.Languages.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.Concept", b =>
                {
                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.ExampleSentence", b =>
                {
                    b.HasOne("Spracher.Modules.Languages.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.ExampleUsage", b =>
                {
                    b.HasOne("Spracher.Modules.Vocabulary.Domain.ExampleSentence", null)
                        .WithMany()
                        .HasForeignKey("ExampleSentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spracher.Modules.Vocabulary.Domain.LexemeSense", null)
                        .WithMany()
                        .HasForeignKey("LexemeSenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.Lexeme", b =>
                {
                    b.HasOne("Spracher.Modules.Languages.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.LexemeFeature", b =>
                {
                    b.HasOne("Spracher.Modules.Vocabulary.Domain.Lexeme", null)
                        .WithMany()
                        .HasForeignKey("LexemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.LexemeSense", b =>
                {
                    b.HasOne("Spracher.Modules.Vocabulary.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spracher.Modules.Languages.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("DefinitionLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spracher.Modules.Vocabulary.Domain.Lexeme", null)
                        .WithMany()
                        .HasForeignKey("LexemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.Pronunciation", b =>
                {
                    b.HasOne("Spracher.Modules.Vocabulary.Domain.Lexeme", null)
                        .WithMany()
                        .HasForeignKey("LexemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.UserVocabularyItem", b =>
                {
                    b.HasOne("Spracher.Modules.Vocabulary.Domain.LexemeSense", null)
                        .WithMany()
                        .HasForeignKey("LexemeSenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.UserVocabularyItemCategory", b =>
                {
                    b.HasOne("Spracher.Modules.Vocabulary.Domain.UserVocabularyItem", null)
                        .WithMany()
                        .HasForeignKey("UserVocabularyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spracher.Modules.Vocabulary.Domain.VocabularyCategory", null)
                        .WithMany()
                        .HasForeignKey("VocabularyCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.VocabularyCategory", b =>
                {
                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.VocabularyList", b =>
                {
                    b.HasOne("Spracher.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.VocabularyListItem", b =>
                {
                    b.HasOne("Spracher.Modules.Vocabulary.Domain.LexemeSense", null)
                        .WithMany()
                        .HasForeignKey("LexemeSenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spracher.Modules.Vocabulary.Domain.VocabularyList", null)
                        .WithMany()
                        .HasForeignKey("VocabularyListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spracher.Modules.Vocabulary.Domain.WordForm", b =>
                {
                    b.HasOne("Spracher.Modules.Vocabulary.Domain.Lexeme", null)
                        .WithMany()
                        .HasForeignKey("LexemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
